---
- name: Set static IP address
  become: yes
  copy:
    dest: "/etc/network/interfaces.d/50-cloud-init.cfg"
    content: |
      auto eth0
      iface eth0 inet static
          address {{ static_ip }}
          netmask 255.255.255.0
          gateway 192.168.0.1
          dns-nameservers 8.8.8.8 8.8.4.4
    mode: '0644'

- name: Backup the current SSH configuration file
  become: yes
  copy:
    src: "/etc/ssh/sshd_config"
    dest: "/etc/ssh/sshd_config.bak"
    mode: '0644'
    backup: yes

- name: Disable password authentication in SSH config
  become: yes
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: '^#?PasswordAuthentication\s+.*'
    line: "PasswordAuthentication no"
    state: present

- name: Disable challenge-response authentication in SSH config
  become: yes
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: '^#?ChallengeResponseAuthentication\s+.*'
    line: "ChallengeResponseAuthentication no"
    state: present

- name: Disable PAM in SSH config
  become: yes
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: '^#?UsePAM\s+.*'
    line: "UsePAM no"
    state: present

- name: Restart SSH service to apply changes
  become: yes
  service:
    name: ssh
    state: restarted