apiVersion: v1
kind: Secret
metadata:
    name: plex-secrets
    namespace: plex
type: Opaque
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:NjHbwyigHBQlEOgAoBplvDUFo1d2mb6+t7E=,iv:t7DNv+t7CPdLL7mz906RU+y1h78GSiVCSjM2hou7gdc=,tag:fztTlHCHqukUQTcBbkQurA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNjVqZExHS2E0NllyNVZY
            dUN2eStXUG84RWp5bEN2RlJUckFnOXVDcmxJCkJnSDJOTVQwMmZZNDNUSVp3dUVD
            TWE1QmFuWnBFbnZURHBQN3hmd1F6bTQKLS0tIFA2aXEwUnhGY1owNk1OSnlZcjNP
            REErN3F5VzFCSE5SeFlSM0JVMWYvVmsKSikrg4Bq73ASxS3G3I0dNE9/RmfOMmPN
            FXlwz/mJnkgf2/8G4rqPGJlNI3smVUpsgPp7gppd/ScgoN1VTGpLyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qkyvh2mrapx0td606w0m8cyc22q2wk4rvpmzvgntpz7eqpx5lvhqmsfap9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T03:55:41Z"
    mac: ENC[AES256_GCM,data:rakF9GXntUhA3WPIJ14Sf5HPtYGJrAxLt5WzZvx+v4qKUx86rTHBCe2kdGeRHaxmr/IBdrvNucBqEiliHb4Irifckp6Q/TVSEn0i5VJD4n4uSHrPTXrmowGSUjU6FMFuhIYJ1RXvx5hfOu124GdctrEsgoG+rZ/yrg4c6JOfrhs=,iv:fCSEo9sRizfQegJaCXKa+wE9zBtmERnnePXsbOXcK1Y=,tag:tfuIGlv6A80ag2cvTqJPkg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: transmission-secrets
    namespace: transmission
type: Opaque
stringData:
    USER: ENC[AES256_GCM,data:E2Ep29k=,iv:vVG7S2gUHF6fk0DlbMxAr+O0++wfaCP4T2tnYr9t1Mk=,tag:uLVPpmXu9pCfKBDGZW+caA==,type:str]
    PASS: ENC[AES256_GCM,data:VNtBta/7pqs=,iv:vHnegt/KtlCQ2UhRWnHoe8k8np6EZLI7ouETY6w+3P8=,tag:E+fOGrB+y+GXrRJvmRJyiw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNjVqZExHS2E0NllyNVZY
            dUN2eStXUG84RWp5bEN2RlJUckFnOXVDcmxJCkJnSDJOTVQwMmZZNDNUSVp3dUVD
            TWE1QmFuWnBFbnZURHBQN3hmd1F6bTQKLS0tIFA2aXEwUnhGY1owNk1OSnlZcjNP
            REErN3F5VzFCSE5SeFlSM0JVMWYvVmsKSikrg4Bq73ASxS3G3I0dNE9/RmfOMmPN
            FXlwz/mJnkgf2/8G4rqPGJlNI3smVUpsgPp7gppd/ScgoN1VTGpLyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qkyvh2mrapx0td606w0m8cyc22q2wk4rvpmzvgntpz7eqpx5lvhqmsfap9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T03:55:41Z"
    mac: ENC[AES256_GCM,data:rakF9GXntUhA3WPIJ14Sf5HPtYGJrAxLt5WzZvx+v4qKUx86rTHBCe2kdGeRHaxmr/IBdrvNucBqEiliHb4Irifckp6Q/TVSEn0i5VJD4n4uSHrPTXrmowGSUjU6FMFuhIYJ1RXvx5hfOu124GdctrEsgoG+rZ/yrg4c6JOfrhs=,iv:fCSEo9sRizfQegJaCXKa+wE9zBtmERnnePXsbOXcK1Y=,tag:tfuIGlv6A80ag2cvTqJPkg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: radarr-secrets
    namespace: radarr
type: Opaque
stringData:
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:6VGnzXrBxXZPB+2rKzqRbCjUzdbL5RC9Y5EgxVKlCW8=,iv:iZfIklgf4PSDmZIfiibqN+FNMKMkCGzDLDus87iGrlI=,tag:CEocNxwqO1NwgQ10O+dZdw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNjVqZExHS2E0NllyNVZY
            dUN2eStXUG84RWp5bEN2RlJUckFnOXVDcmxJCkJnSDJOTVQwMmZZNDNUSVp3dUVD
            TWE1QmFuWnBFbnZURHBQN3hmd1F6bTQKLS0tIFA2aXEwUnhGY1owNk1OSnlZcjNP
            REErN3F5VzFCSE5SeFlSM0JVMWYvVmsKSikrg4Bq73ASxS3G3I0dNE9/RmfOMmPN
            FXlwz/mJnkgf2/8G4rqPGJlNI3smVUpsgPp7gppd/ScgoN1VTGpLyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qkyvh2mrapx0td606w0m8cyc22q2wk4rvpmzvgntpz7eqpx5lvhqmsfap9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T03:55:41Z"
    mac: ENC[AES256_GCM,data:rakF9GXntUhA3WPIJ14Sf5HPtYGJrAxLt5WzZvx+v4qKUx86rTHBCe2kdGeRHaxmr/IBdrvNucBqEiliHb4Irifckp6Q/TVSEn0i5VJD4n4uSHrPTXrmowGSUjU6FMFuhIYJ1RXvx5hfOu124GdctrEsgoG+rZ/yrg4c6JOfrhs=,iv:fCSEo9sRizfQegJaCXKa+wE9zBtmERnnePXsbOXcK1Y=,tag:tfuIGlv6A80ag2cvTqJPkg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secrets
    namespace: sonarr
type: Opaque
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:ONY2GaTdbe6PgapgZbtQMMHFh032ba+X9tF4CU/ZfS4=,iv:uDdSuSam/FDZYsYBP6S/JxW8Ju4LL3UQaF6d4+tkfr8=,tag:9VVRexz1GWWfROvbtE0SnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNjVqZExHS2E0NllyNVZY
            dUN2eStXUG84RWp5bEN2RlJUckFnOXVDcmxJCkJnSDJOTVQwMmZZNDNUSVp3dUVD
            TWE1QmFuWnBFbnZURHBQN3hmd1F6bTQKLS0tIFA2aXEwUnhGY1owNk1OSnlZcjNP
            REErN3F5VzFCSE5SeFlSM0JVMWYvVmsKSikrg4Bq73ASxS3G3I0dNE9/RmfOMmPN
            FXlwz/mJnkgf2/8G4rqPGJlNI3smVUpsgPp7gppd/ScgoN1VTGpLyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qkyvh2mrapx0td606w0m8cyc22q2wk4rvpmzvgntpz7eqpx5lvhqmsfap9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T03:55:41Z"
    mac: ENC[AES256_GCM,data:rakF9GXntUhA3WPIJ14Sf5HPtYGJrAxLt5WzZvx+v4qKUx86rTHBCe2kdGeRHaxmr/IBdrvNucBqEiliHb4Irifckp6Q/TVSEn0i5VJD4n4uSHrPTXrmowGSUjU6FMFuhIYJ1RXvx5hfOu124GdctrEsgoG+rZ/yrg4c6JOfrhs=,iv:fCSEo9sRizfQegJaCXKa+wE9zBtmERnnePXsbOXcK1Y=,tag:tfuIGlv6A80ag2cvTqJPkg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: discord-secrets
    namespace: discord
type: Opaque
stringData:
    DISCORD_TOKEN: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNjVqZExHS2E0NllyNVZY
            dUN2eStXUG84RWp5bEN2RlJUckFnOXVDcmxJCkJnSDJOTVQwMmZZNDNUSVp3dUVD
            TWE1QmFuWnBFbnZURHBQN3hmd1F6bTQKLS0tIFA2aXEwUnhGY1owNk1OSnlZcjNP
            REErN3F5VzFCSE5SeFlSM0JVMWYvVmsKSikrg4Bq73ASxS3G3I0dNE9/RmfOMmPN
            FXlwz/mJnkgf2/8G4rqPGJlNI3smVUpsgPp7gppd/ScgoN1VTGpLyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qkyvh2mrapx0td606w0m8cyc22q2wk4rvpmzvgntpz7eqpx5lvhqmsfap9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T03:55:41Z"
    mac: ENC[AES256_GCM,data:rakF9GXntUhA3WPIJ14Sf5HPtYGJrAxLt5WzZvx+v4qKUx86rTHBCe2kdGeRHaxmr/IBdrvNucBqEiliHb4Irifckp6Q/TVSEn0i5VJD4n4uSHrPTXrmowGSUjU6FMFuhIYJ1RXvx5hfOu124GdctrEsgoG+rZ/yrg4c6JOfrhs=,iv:fCSEo9sRizfQegJaCXKa+wE9zBtmERnnePXsbOXcK1Y=,tag:tfuIGlv6A80ag2cvTqJPkg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
type: Opaque
stringData:
    HOMEPAGE_VAR_PLEX_TOKEN: ENC[AES256_GCM,data:DfI3ETTxP+gXmSWEXKH3jN9EurCduEs+rL4=,iv:OiGZxjm0r6PIpmgBej7IQGZWPK9/0U5ckZImUq2n92w=,tag:DcfkGGDzehzN0ZVO3ilc7Q==,type:str]
    HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:Jtq/o6vdb8X0WkhThPJcGfh+GpXjWmPBlB1n7GbSmU8=,iv:NNAe8al/G85rqRgV8Gi9t0J2YPZcHUjd53jkVcZ9FQg=,tag:c+M4XSDlhd39tJ91050U4w==,type:str]
    HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:6eClzLMh0VpJkgyBscPicLJPf2rXviZ/cnqlEhEnw20=,iv:NJd2AhdLdlZmNFJEiHBAoonbkfzGPrG6Dk3Iwre9ijQ=,tag:K/9HRG1VSUVmEN5Tj9MVYQ==,type:str]
    HOMEPAGE_VAR_OVERSEERR_KEY: ""
    HOMEPAGE_VAR_TRANSMISSION_USER: ENC[AES256_GCM,data:gMnlffg=,iv:MlGhtwAkxOeLbQRKO25EajvUXTeZIUB5sLVVRluRuLc=,tag:uOokbW1GJDsiV/5J2GuRQg==,type:str]
    HOMEPAGE_VAR_TRANSMISSION_PASS: ENC[AES256_GCM,data:glOfGpb3IZc=,iv:NpROBk6qegMWNc/DtYlBzYdXavqZ36+94hNjowFe4VI=,tag:EKEKZHHK9DWKJQhHHHbX7Q==,type:str]
    HOMEPAGE_VAR_FINNHUB: ENC[AES256_GCM,data:S4m72ccEUUFOjfOlMUg1/ZfjShjwml9y2FsTVg8il+QKnXY6j8pT5w==,iv:X5XeF/U4Tp4URYkW/QTHuKSJaLmOEOFnPCXWtF9eONg=,tag:awr6qlm7OOUCvRMsDltGRw==,type:str]
    HOMEPAGE_VAR_OPENWEATHERMAP: ENC[AES256_GCM,data:xC9alne5C9dg3/NYbmqN/UZKs+YHB21tbTwloiRDvuo=,iv:gtu5G4APs+DSs3kcxtsntfeZJlzpxbOtK+dsf1YaNiI=,tag:oXX2tYCljiTfJ90h8/LX1A==,type:str]
    HOMEPAGE_VAR_WEATHERAPI: ENC[AES256_GCM,data:e8w416mOPAb8LS+rbbskHnAFPukWtRjxftbSp+E4Gw==,iv:2aq/VUT0B+eqqkFaqT5en42x6epbqbiRnGT+fImussY=,tag:c3b2zw74FDGq0Hmc407ZDQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNjVqZExHS2E0NllyNVZY
            dUN2eStXUG84RWp5bEN2RlJUckFnOXVDcmxJCkJnSDJOTVQwMmZZNDNUSVp3dUVD
            TWE1QmFuWnBFbnZURHBQN3hmd1F6bTQKLS0tIFA2aXEwUnhGY1owNk1OSnlZcjNP
            REErN3F5VzFCSE5SeFlSM0JVMWYvVmsKSikrg4Bq73ASxS3G3I0dNE9/RmfOMmPN
            FXlwz/mJnkgf2/8G4rqPGJlNI3smVUpsgPp7gppd/ScgoN1VTGpLyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qkyvh2mrapx0td606w0m8cyc22q2wk4rvpmzvgntpz7eqpx5lvhqmsfap9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T03:55:41Z"
    mac: ENC[AES256_GCM,data:rakF9GXntUhA3WPIJ14Sf5HPtYGJrAxLt5WzZvx+v4qKUx86rTHBCe2kdGeRHaxmr/IBdrvNucBqEiliHb4Irifckp6Q/TVSEn0i5VJD4n4uSHrPTXrmowGSUjU6FMFuhIYJ1RXvx5hfOu124GdctrEsgoG+rZ/yrg4c6JOfrhs=,iv:fCSEo9sRizfQegJaCXKa+wE9zBtmERnnePXsbOXcK1Y=,tag:tfuIGlv6A80ag2cvTqJPkg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: yamtrack-secrets
    namespace: yamtrack
type: Opaque
stringData:
    SECRET: ENC[AES256_GCM,data:hXP0HluqkhfRAprGtbU5BlOIIIYPiWexDtsky8i64WTE4k7QRSrLoPmifbqA8bZpcwFXurR3fg0QNVmMkkYN/A==,iv:dx0ltgcrTebPNcoy86iKR5tB5Mu5yh0/UWXDqXrTryU=,tag:x/avmV+4OXBUyvpAWXzJ6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNjVqZExHS2E0NllyNVZY
            dUN2eStXUG84RWp5bEN2RlJUckFnOXVDcmxJCkJnSDJOTVQwMmZZNDNUSVp3dUVD
            TWE1QmFuWnBFbnZURHBQN3hmd1F6bTQKLS0tIFA2aXEwUnhGY1owNk1OSnlZcjNP
            REErN3F5VzFCSE5SeFlSM0JVMWYvVmsKSikrg4Bq73ASxS3G3I0dNE9/RmfOMmPN
            FXlwz/mJnkgf2/8G4rqPGJlNI3smVUpsgPp7gppd/ScgoN1VTGpLyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qkyvh2mrapx0td606w0m8cyc22q2wk4rvpmzvgntpz7eqpx5lvhqmsfap9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T03:55:41Z"
    mac: ENC[AES256_GCM,data:rakF9GXntUhA3WPIJ14Sf5HPtYGJrAxLt5WzZvx+v4qKUx86rTHBCe2kdGeRHaxmr/IBdrvNucBqEiliHb4Irifckp6Q/TVSEn0i5VJD4n4uSHrPTXrmowGSUjU6FMFuhIYJ1RXvx5hfOu124GdctrEsgoG+rZ/yrg4c6JOfrhs=,iv:fCSEo9sRizfQegJaCXKa+wE9zBtmERnnePXsbOXcK1Y=,tag:tfuIGlv6A80ag2cvTqJPkg==,type:str]
    version: 3.13.3
