repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.0
    hooks:
      - id: terraform_fmt
        args: ['--recursive']
      - id: terraform_docs
        args: ['--recursive']
