# SOPS-encrypted. Edit with: sops apps/base/yamtrack/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: yamtrack-secrets
    namespace: yamtrack
type: Opaque
stringData:
    SECRET: ENC[AES256_GCM,data:X9t5ZuJI/RqMo5nxtwGlixtYJg+dTrkpD4Xgg6oHk+AZXLnBfZ6Gnr3fynjDhqYcuiVOvUhYKtSvCEvK86DgZw==,iv:2UKOd+wdnfe8jCHhQaDb5H0OIyCrujiNstC3EOtHJxE=,tag:DrYau+m5V+mIMRBwIg8KIA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbnJHRVJFbHZjRTRWaGpH
            SWtDdzlleGs4T1VUNGQxeGtLV0lhc0RHWGlvCks3K242Y2hHQ0IrK0pIK1VsT2xi
            cUJ2ZVlQZHZYbmNrRUMvcXY4a3lnODgKLS0tIHhwR0FTaUk2TWVBelpxY2FQaFVi
            eTBaZ0F5ZHpDUDNKNy82aFBLbzQwSm8KNieAa/95cmrXDsneE+HnF1SEIm8Q3cdp
            TNciJmKM6EsPAEh9MGu4MavF4ZqnjJzZ0Qc9ts3oT1UnC3aJPcfXdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qkyvh2mrapx0td606w0m8cyc22q2wk4rvpmzvgntpz7eqpx5lvhqmsfap9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T14:51:19Z"
    mac: ENC[AES256_GCM,data:AyslUYDh7uqn1fFi9XY/nSVu6MwE8lIPDZaJwrO/qrILyXNN0E0SHuxwHTniUnSSFw2MJuriVVddfHAa8+L6vCsRT5wAaAw2H9MX1xU8uQpHHwYiuKLQHX6/BraocJpxkLlXPAt9XRucwXn4BnoIdId0eQ3WY2PI7a8vGx7MSak=,iv:VloiLMqyEQysq4h1n4poK4fTu5wU7zp3NVyF9Qy8GFs=,tag:WPIHDcfdbv8hQEIVCNKLBQ==,type:str]
    version: 3.13.3
