variable "kubeconfig" {}
variable "domain_root" {}
variable "node_ip" {}
variable "service_list" {}
variable "kubecost_token" {}
variable "discord_image" {}
variable "media_mount" {}
variable "github_username" {}
variable "github_pat" {}
variable "plex_token" {}