# https://github.com/truecharts/public/blob/master/charts/stable/transmission/values.yaml
persistence:
  config:
    enabled: true
    hostPath: ${transmission_config}
    mountPath: "/config"
  downloads:
    enabled: true
    type: hostPath
    hostPath: "${plexdir_downloads}/complete"
    mountPath: "/downloads/complete"
    readOnly: false
  incomplete:
    enabled: true
    type: hostPath
    hostPath: "${plexdir_downloads}/incomplete"
    mountPath: "/downloads/incomplete"
    readOnly: false

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            USER: ${username}
            PASS: ${password}

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

ingress:
  main:
    ingressClassName: nginx
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/whitelist-source-range: "127.0.0.1/24"
    integrations:
      homepage:
        enabled: ${homepage_enabled}
      traefik:
        enabled: false
    hosts:
      - host: ${full_path}
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - ${full_path}
        secretName: ${tls_secret}
