# SOPS-encrypted. Edit with: sops apps/base/discord/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: discord-secrets
    namespace: discord
type: Opaque
stringData:
    DISCORD_TOKEN: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UlpsUUZzWmw3QnJxZkF6
            SGx0b095c2RkaTFDbHAvL0d0S0R2bU1MbUZJCko2QWJWNWZORUhtbVNoZm0yNnpR
            eFlYM1pOdmYwc1E3dnhVQ1pTQkt5bzQKLS0tIFo4MUhWOXBvK3E4a1Qrak5KRG5i
            c2xuMWs1N09RSlQ4NG5oSG1KZnF1bXcKOrvEakybM7Nd04B09lLA0S5bazOl5GiA
            jxb+s3W95z+IW7CzajPUvGS4oA1R4UeQX9ndTRKLOcC9n1I5of+0dA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qkyvh2mrapx0td606w0m8cyc22q2wk4rvpmzvgntpz7eqpx5lvhqmsfap9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T14:51:19Z"
    mac: ENC[AES256_GCM,data:67KBqyOXr1W4QThxTVDCjGP6V0ApDWULpJDisjX2MGDE28BRflDTKunTtinrQjIvwspkTZxaMOnHf9QvPEfMU1xMSBfMlurFbFjVRX2IuCGVVfZMsiSsX7zUd3W9O6yDqaHSx6eRgrL+nFbWTHbm6xeGikYBvDtSWL8uwMdkUio=,iv:fZ/u0EyfmO6I5Nma2ciB3TEk9F2MZdHgSQhCEJnxtNQ=,tag:Ue71z5CPJcVv1SaHaE3K6A==,type:str]
    version: 3.13.3
