# SOPS-encrypted. Edit with: sops apps/base/discord/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: discord-secrets
    namespace: discord
type: Opaque
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:UKOejN6D7xCTzE6OCXwL+QK7fyCqKpT353DxTlVqj2PCbht2hmvSLJxPt96pivTjqekOWuxq105IHJ47Hr2XkfC0gcckLg==,iv:vvXS6UFAzodei+G9kPMhQ5L8UwGquW/XMCUI4McUG6Q=,tag:V55R12dQXjAKPyN3uacv3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UlpsUUZzWmw3QnJxZkF6
            SGx0b095c2RkaTFDbHAvL0d0S0R2bU1MbUZJCko2QWJWNWZORUhtbVNoZm0yNnpR
            eFlYM1pOdmYwc1E3dnhVQ1pTQkt5bzQKLS0tIFo4MUhWOXBvK3E4a1Qrak5KRG5i
            c2xuMWs1N09RSlQ4NG5oSG1KZnF1bXcKOrvEakybM7Nd04B09lLA0S5bazOl5GiA
            jxb+s3W95z+IW7CzajPUvGS4oA1R4UeQX9ndTRKLOcC9n1I5of+0dA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qkyvh2mrapx0td606w0m8cyc22q2wk4rvpmzvgntpz7eqpx5lvhqmsfap9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T00:02:10Z"
    mac: ENC[AES256_GCM,data:3WH4En/7nXpUMLH87eZiOsKcHb6BNU4AuWd0lnmHiq1G9QXshg5D2vYfvycufG0wXWF8BuX7c7Xwy5gGpl2+q40ZfRE6ssRyaWfv0ABoK47+4nBIRLbmnXyMgfCAqVuUX8+8trNvCcKKFOqw/xjH4KreqRxaVfI4lMAPR9AdKMc=,iv:4xFIJT+MHX2oE2/fOnazK8vK6WsBZaXtlzCfgdRjFcA=,tag:40KDp3SzcY0/7zpclznYjw==,type:str]
    version: 3.13.3
