---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Arr:
  - Sonarr:
      icon: sonarr.png
      href: https://sonarr.${domain_root}/
      description: Series management
      widget:
        type: sonarr
        url: https://sonarr.sonarr.svc.cluster.local
        key: ${apikey_sonarr}
  - Radarr:
      icon: radarr.png
      href: https://radarr.${domain_root}/
      description: Movie management
      widget:
        type: radarr
        url: https://radarr.radarr.svc.cluster.local
        key: ${apikey_radarr}

- Media:
  - Plex:
      icon: plex.png
      href: https://plex.${domain_root}/
      description: Plex
      server: plex
      container: plex