---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Arr:
    - Sonarr:
        href: http://sonarr.${domain_root}/
        description: Sonarr
    - Radarr:
        href: http://radarr.${domain_root}/
        description: Radarr

- Media:
    - Plex:
        href: http://plex.${domain_root}/
        description: Plex