---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  finnhub: "${finnhub}"
  openweathermap: "${openweathermap}"
  weatherapi: "${weatherapi}"
