---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/widgets

- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short
      hour12: true

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank

- weatherapi:
    label: Home
    units: imperial
    cache: 5

- stocks:
    provider: finnhub
    watchlist:
      ${stock_watchlist}

- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
    nodes:
      show: true
      cpu: true
      memory: true
