---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/widgets

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank

- openweathermap:
    label: Atlanta
    units: imperial
    provider: openweathermap
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format:
      maximumFractionDigits: 0

- stocks:
    provider: finnhub
    watchlist: 
      ${stock_watchlist}

- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
    nodes:
      show: true
      cpu: true
      memory: true