# SOPS-encrypted. Edit with: sops apps/base/sonarr/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secrets
    namespace: sonarr
type: Opaque
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:CZT8YPPGWvoNNw3pkckw+tRGrS8PL5oJJUh2YO5tGNg=,iv:V6xyAjBIQDXWS1aHz4ZIzJ8Vg67cm7lYVRe7p4jl60s=,tag:aKmTwUIARmaWdDAJkgT8hA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYjVZaGJpbFRqZzFBMnlW
            UXBNYk9Oa0xvNlhOUkZEQTRRZjBLZUVjOWhZCkVSeWFlWXhsck1CVWtleElPcWVP
            UFZybXdlSTJkY1piRmJvRGNOSFU5RFEKLS0tIEpyTE93TXlnWkxMWXZuNXdZQkND
            eVorZzJHaWFLRVkxcGxwQlY1bW93S2MKwApy7Kf4XdsDk+tH5gesHBpySWSiit4n
            JM1hWISJ2AiamHRnkBwQzZPuwp8O9mq5mNx6Wdrmu9NqxXJm9nyn7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qkyvh2mrapx0td606w0m8cyc22q2wk4rvpmzvgntpz7eqpx5lvhqmsfap9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T14:51:19Z"
    mac: ENC[AES256_GCM,data:11DneA3SuiHoTgOgpfVkq+Sbm8n30LBt+IDM9oSt8tgSVrL+OHbC0+zldMPUUogwwnw+Ozig3wDn2aCGMNCwCenLAUUqft+wdcmg3IBBFvlclVc6rwDNMu6DNiP3uopTI9Y6I79ecxMA9s/NFIDraY9Sw70GGK9DTNT0AzGW8T4=,iv:njcOhYTnandaMlrLyD1F2xZ489jELHb64jwCDkdHXwM=,tag:kU+fPQw8yv13a5xThjYuWA==,type:str]
    version: 3.13.3
