# SOPS-encrypted. Edit with: sops apps/base/radarr/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: radarr-secrets
    namespace: radarr
type: Opaque
stringData:
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:BIYyeXFoR+qZxrEwz/G27jEZy/yAB37Kl0H2jrhF44A=,iv:QM3Vid5FJrSHJSo98jvZlVC67hYHIyOfuFgwBasw24o=,tag:hEgRJvI0mopjoxDcxNr1VQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoblZwR0lRM2lDMCtIMjFL
            UHBESkhqRC9ucm5ZY2JBRkR6QUU2RUN0Smd3CitkTHlPWUE2R0pkc3d0Y3pndE5G
            cW1QV05GSW0vbkp6dkVnQlNtZXdUU0UKLS0tIGIvSXlvcDEyNUF5VjhPOGdtUjJF
            RGdUbFdSQm1mZGhnVjUwZWRsUjFoZEEKC2+cU3a+d+wHJXASY4vr9YgY2OgYOoOT
            buS6kFZ4xppEcERJcS/XnhHJB2FSjebIbwNLuXNMiFRBv1rQPwewTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qkyvh2mrapx0td606w0m8cyc22q2wk4rvpmzvgntpz7eqpx5lvhqmsfap9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T14:51:19Z"
    mac: ENC[AES256_GCM,data:7GSMwOlbaVv57JykIqscMIr2WgI08tiIQSNnVXWfgkcpOR6MU6gnpFQ1pkfbe7RibnHbNcX/yxRJrsXi27NylpbtwrF6rpDz4nNbgi04yxDrvQvlzYCc0zmov1dr0VFIDQm/bTMHVFsfW16Aq0iZ8Ltxo09wZpjcpar2NuRKcJk=,iv:JjxKHsD15DkALKPORSoBZVc6xkknCE+ElSj3mDnlHhE=,tag:0xMnzntitnoW0QiIxR8NOA==,type:str]
    version: 3.13.3
