globalArguments:
  - "--global.sendAnonymousUsage=false"

service:
  type: NodePort

ports:
  web:
    nodePort: 30080
    redirectTo:
      port: websecure
  websecure:
    nodePort: 30443
    tls:
      enabled: true
