# SOPS-encrypted. Edit with: sops apps/base/homepage/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
type: Opaque
stringData:
    HOMEPAGE_VAR_PLEX_TOKEN: ENC[AES256_GCM,data:Wx5s15yVtp9k3aHxSTVG7j+AOVDSKm/XOZY=,iv:DEyLBg9RZS0AMvCgXyRxGOmOX6g446O2a/vedRxk8DI=,tag:AHLxSjjy6soPNj9t2uhzZg==,type:str]
    HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:JuiPXTSLOhVW6TPJIgt2oxobEOSbVWwHgXqGx0DSCYM=,iv:UTbrHg/ViGNPkPlc2bxt9Y4veSY7pgM8MLG1ZVReIfc=,tag:IoVF3dF2GRnEMslrECR0qA==,type:str]
    HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:GRRL6qJPFh0JlxBtc1bhxxR/HF85Rn+vJA9lCBPG74o=,iv:l7vB2liPFaEW+L3TUiSHICvJA577ypQJ10W9Jv6Sfv8=,tag:74CJPU7X/Px+B93PU3pkSg==,type:str]
    HOMEPAGE_VAR_OVERSEERR_KEY: ""
    HOMEPAGE_VAR_TRANSMISSION_USER: ENC[AES256_GCM,data:xXEgiC8=,iv:tBaJOh/YL2Yss/XaZQd512kDse5zm5ugM7uGWRbMwHc=,tag:dJY9STjS2ze44Zjl8IkZYw==,type:str]
    HOMEPAGE_VAR_TRANSMISSION_PASS: ENC[AES256_GCM,data:VJhIqmUx7mA=,iv:+iDk2pyuXu5No2yIqAE7JSww6z1z0jUUJZz2/TpTDow=,tag:MKTXmtduuHAI2VHsGmiacg==,type:str]
    HOMEPAGE_VAR_FINNHUB: ENC[AES256_GCM,data:Y4qOtSxfXlNu4K0q0xAhITStvnLdwnpKdQV4Zyu/Pm+xCef9cy9rNg==,iv:f1hvGhC0HDpsuTIKPgcCWZ9gZXXtTdWwjfgu5IQbg2s=,tag:g7exJ2jM/yz7/+SHUghPxg==,type:str]
    HOMEPAGE_VAR_OPENWEATHERMAP: ENC[AES256_GCM,data:joRY9FrjcfU0twzb7p0OD3uo/oqifUsAITgUdW3NvYI=,iv:ezwNrEIF2wJexDN5O/HZasOfeNXuprVDMGre3wc6XOQ=,tag:L5NtuFBBJb6SJZ0WM2mv7w==,type:str]
    HOMEPAGE_VAR_WEATHERAPI: ENC[AES256_GCM,data:NuAnDbD3AU9f6i6xq2HUernI39bmDyA6gUcJaI799g==,iv:bAc6lEoTjPl9bOVdBwNV1uDSUyqS/6xocPUlvkgUy54=,tag:WvvxVYtFIgk8UdP8RCK/0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVkNReXJWbjZ3WnR6ODQr
            NGpERlJJSWdVMC9XRUl0LzhodXBRckFvaFJNCk5ORDY1cjhUOXlnMWsybThIVHNT
            MWJsNk1hckRxOGE5enJrWExNNm1QcDAKLS0tIE5abVZyYnQ1TFd5dkUxeFVKM1NG
            Nk9ZZDV1RE1qSzBoUXZZeVE3bmJ6eWMKExPcKDmIJxpA6DwOQI2RquEkInjmOl/P
            8hvg/dYGjOyRaw3KvLVnjPudgSKF9nGGK3CKpe2+ALUqT2LhYMYhXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qkyvh2mrapx0td606w0m8cyc22q2wk4rvpmzvgntpz7eqpx5lvhqmsfap9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T14:51:19Z"
    mac: ENC[AES256_GCM,data:un2SMw21IupnZsU/UN/O5AlgFMmj8KBXcNNZ4wTdOEzFf8ssHK4WL9UQlnW2Z+SSNdQGB5aSmNjQShZNWKJ2LCpCSNH3aBHG5FzVAudXvTpNY2ZMMV4izEACHzn0gxuTqCUANY/B/9ymSr9u1wrVmC+gQg7wiiPiuJplKMB8Ehk=,iv:yqTHSjmF06uHkYeWdryqIx1ypJn7LTbcVjpFTkx2asA=,tag:25SLrooZDTmyIAsBJSpVLg==,type:str]
    version: 3.13.3
