---
- name: Create network check script
  become: yes
  copy:
    dest: /usr/local/bin/check_network.sh
    mode: '0755'
    content: |
      #!/bin/bash
      if ! ping -c 1 8.8.8.8 &> /dev/null; then
          systemctl restart networking
      fi

- name: Create cron job to check network every 10 minutes
  become: yes
  cron:
    name: "Network check"
    job: "/usr/local/bin/check_network.sh"
    minute: "*/10"
