---
- name: Check if Helm is installed
  command: helm version
  register: helm_check
  failed_when: helm_check.rc != 0
  changed_when: false
  ignore_errors: true  # allow task to continue if helm is not found

- name: Download Helm installation script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0755'
  when: helm_check.rc != 0

- name: Run Helm installation script
  command: /tmp/get_helm.sh
  become: yes
  args:
    creates: /usr/local/bin/helm
  register: helm_install_result
  changed_when: false
  when: helm_check.rc != 0

- name: Add /usr/local/bin to PATH if needed
  become: yes
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=$PATH:/usr/local/bin'
  when: helm_check.rc != 0 and helm_install_result.rc == 0

- name: Clean up Helm installation script
  file:
    path: /tmp/get_helm.sh
    state: absent
  when: helm_check.rc != 0 
