---
- name: Export evnironment variables
  import_tasks: envars.yml

- name: Create .kube directory for user
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.kube"
    state: directory
    mode: 0755

- name: Create local directory
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: 0755
  delegate_to: localhost

- name: Download K3s installation script
  become: yes
  get_url:
    url: https://get.k3s.io
    dest: /tmp/install_k3s.sh
    mode: '0755'

- name: Initialize k3s Control Plane
  become: yes
  command: sh /tmp/install_k3s.sh
  environment:
    K3S_KUBECONFIG_MODE: "644"
    INSTALL_K3S_EXEC: "--disable=traefik"
  register: k8s_init
  failed_when: k8s_init.rc != 1 and k8s_init.rc != 0

- name: Copy kubeconfig with owner and permissions
  become: yes
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ ansible_facts['env']['HOME'] }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    remote_src: yes

- name: Copy Kubeconfig to local machine
  ansible.builtin.fetch:
    src: ~/.kube/config
    dest: /tmp/k3s_bootstrap.yaml
    flat: yes

- name: Get server IP address
  shell: "hostname -I | awk '{print $1}'"
  register: server_ip
    
- name: Update kubeconfig with control IP (on host machine)
  replace:
    path: /tmp/k3s_bootstrap.yaml
    regexp: "https://127.0.0.1:6443"
    replace: "https://{{ server_ip.stdout }}:6443"
  delegate_to: localhost

- name: Copy kubeconfig into place (on host machine)
  copy:
    src: /tmp/k3s_bootstrap.yaml
    dest: ~/.kube/config
  delegate_to: localhost

- name: Add permanent alias for kubectl
  lineinfile:
    path: /home/{{ ansible_user }}/.bashrc
    line: "alias k='kubectl'"
    create: yes
  become: false

- name: Get k3s join token
  command: "cat /var/lib/rancher/k3s/server/node-token"
  become: yes
  register: k3s_token

- name: Retrieve kubeadm join command
  command: echo "curl -sfL https://get.k3s.io | K3S_URL=https://{{ server_ip.stdout }}:6443 K3S_TOKEN={{ k3s_token.stdout }} sh -"
  register: kubeadm_join_command

- name: Install Helm
  import_tasks: helm.yml

- name: Configure rest of settings
  import_tasks: config.yml

- name: Create cronjobs
  import_tasks: cronjobs.yml