# SOPS-encrypted. Edit with: sops apps/base/transmission/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: transmission-secrets
    namespace: transmission
type: Opaque
stringData:
    USER: ENC[AES256_GCM,data:DRXSY8g=,iv:b/5H//TuGDs5lB700ZVJH7s56ijqU8nvcDgYiZG1ocs=,tag:NXMWyV7DQG4Tprp2csta+Q==,type:str]
    PASS: ENC[AES256_GCM,data:E/WTU6RXe/k=,iv:1EUo7jf8VIR6Vh5zK9cfoS8nLZxHEfHGVttqyw9MkWY=,tag:iwsI6ptBenzMZEUTW9WPrg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWFo4YUpRSTVPQ3l6aVFL
            OE54dWtqUXNFelpRdUdyMG13N3ZiMmdrK2owCmkrWkNCRmkxWWo2ZGNxTzFScTJO
            WTkzV1NWd25ma0F4V2NjWXNwbmhkTFUKLS0tIFFpMW8vaFdMOUcvUkhrWVJVYWRG
            cXJaSFU5eDFISFNWaUViZmxYQk56L1EKCcgNDP7NOKni0x0L0meRqvYyu1pngyZD
            ar9d9SO6+AYOZsWt40ZDTfv6Azyl9BmVuTyjWhBHGsReZ68cbJe05g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qkyvh2mrapx0td606w0m8cyc22q2wk4rvpmzvgntpz7eqpx5lvhqmsfap9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T14:51:19Z"
    mac: ENC[AES256_GCM,data:levY8v06JOLKchmJfo0kFqWuBDJ5kpe63t7Lovzk6h/V+CRmyvmsMHEDIzVyFIhDe4T2IY8IJ/lFnZnRqso8VOtsrXyYRbfBEiOPK5v+X7B4gFh+c1xVt4D7zlCc+hSn90MNfSnvVJAKEZx5/bRdQp2JPxPB7EbEbYxLKgEtv8k=,iv:mlCtwNT8Vl1IdEtsTHb80VqbvszbD6k+Nl6/IOuAVjc=,tag:G9JjioDo7q1JJZaxhANLsw==,type:str]
    version: 3.13.3
