name: Terraform Format and Docs

on:
  push:
    paths:
      - 'terraform/**.tf'
      - 'terraform/**.md'
  pull_request:

jobs:
  fmt-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Format Terraform
        run: terraform fmt -recursive terraform/

      - name: Generate Terraform Docs
        uses: terraform-docs/gh-actions@v1.4.0
        with:
          working-dir: terraform/
          output-file: README.md
          output-method: inject
          recursive: true
