# SOPS-encrypted. Edit with: sops apps/base/plex/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: plex-secrets
    namespace: plex
type: Opaque
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:EeIRRbm2yLfzR8xNDSwebpvu5RB9u0OTHgE=,iv:VJQJLWyWPdSmh/QrZsThsyW/vEsDvgRU5MZOeb0aMKU=,tag:Oyhyz8SRgwWr2yQGfsnpkA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUN290UUtFWlNGUEoxMkUz
            SkQwQ0xtald0VExNeXpyM01PZDdac0FKdkgwCldDcDBtWGlab1dSb2h4d3FrM00v
            bHFZUHUwTW5FT25KdHNSYnVGRWNhMlkKLS0tIDFLSXZpckoyNXE1N3VObGs2a1U4
            OXV1NXEvWi82ajdJVEdzc1NMa0ZFNjQKDdIsiSsuYUcNhRW/JLKR8kIPYXug8NDL
            hC2B2f489SJ7Mi5CH4F4VHrXB/V7VCMu20EzS1nJ94FOvnRtM5/HtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qkyvh2mrapx0td606w0m8cyc22q2wk4rvpmzvgntpz7eqpx5lvhqmsfap9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T14:51:19Z"
    mac: ENC[AES256_GCM,data:gaqyuqf9mX0/79PZp2lZNPmADkhVEUqjm64tPqp/qh2c24YK7WE2nlkP3vhwGgKdoH9cnJ/6H/UgchgS5LIhu62JchkM4v8anLiuwyv2o7oIGI406YcRhrekA9l1ib2Ei36u82RTWIpQmDH5NEUnu66v+riGqmTWpdg18r+9HNg=,iv:i+gcyYkN70FoasZyQUoYoCrgVw884eewR/k7YcD/WZs=,tag:czwENUTHKYTfmKL5ZtuAkQ==,type:str]
    version: 3.13.3
